// [true, false]
var words = [
    ["azan", "adzan"],
    ["azab", "adzab"],
    ["akhlak", "ahlak"],
    ["akikah", "akekah"],
    ["akhirat", "akherat"],
    ["ambeien", "ambeyen"],
    ["ambulans", "ambulan"],
    ["amfibi", "ampibi"],
    ["analisis", "analisa"],
    ["angpau", "angpao"],
    ["antre", "antri"],
    ["artefak", "artifak"],
    ["arbitrase", "arbitrasi"],
    ["akidah", "aqidah"],
    ["atmosfer", "atmosfir"],
    ["bakpao", "bakpau"],
    ["baterai", "batere"],
    ["bedung", "bedong"],
    ["bumper", "bemper"]
    ["beraneka ragam", "beraneka-ragam"],
    ["beranak pinak", "beranak-pinak"],
    ["beranak bercucu", "beranak-bercucu"],
    ["beramah-tamah", "beramah tamah"],
    ["beramai-ramai", "beramai ramai"],
    ["bengkuang", "bengkoang"],
    ["bernegosiasi", "bernegoisasi"],
    ["beri tahu", "beritahu"],
    ["berdukacita", "berduka cita"],
    ["bekerja sama", "berkerjasama"],
    ["bekerja sama", "berkerja sama"],
    ["bernapaskan", "bernafaskan"],
    ["barzanji", "berzanji"],
    ["bilamana", "bila mana"]
    ["biomolekuler", "biomolekular"],
    ["penatu", "binatu"],
    ["bonafide", "bonafid"],
    ["bolpoin", "bolpen"],
    ["berengsek", "brengsek"],
    ["berewok", "brewok"],
    ["berangus", "brangus"],
    ["berambang", "brambang"],
    ["bungkuk", "bongkok"],
    ["berandal", "brandal"],
    ["bulu tangkis", "bulutangkis"],
    ["budi daya", "budidaya"],
    ["cakra buana", "cakrabuana"],
    ["capai", "capek"],
    ["capcai", "capcay"],
    ["cekik", "cekek"],
    ["cebur", "cebar-cebur"]
];

var words_count = words.length;
