// [true, false]
var words = [
    ["azan", "adzan"],
    ["azab", "adzab"],
    ["akhlak", "ahlak"],
    ["akikah", "akekah"],
    ["akhirat", "akherat"],
    ["alpukat", "alpokat"],
    ["Al-Qur'an", "Al-Quran"],
    ["lemari", "almari"],
    ["ambeien", "ambeyen"],
    ["ambulans", "ambulan"],
    ["amfibi", "ampibi"],
    ["amonia", "amoniak"],
    ["analisis", "analisa"],
    ["angpau", "angpao"],
    ["antre", "antri"],
    ["artefak", "artifak"],
    ["arbitrase", "arbitrasi"],
    ["akidah", "aqidah"],
    ["apotek", "apotik"],
    ["atmosfer", "atmosfir"],
    ["bakpao", "bakpau"],
    ["baterai", "batere"],
    ["bedung", "bedong"],
    ["bumper", "bemper"],
    ["bengkuang", "bengkoang"],
    ["barzanji", "berzanji"],
    ["biomolekuler", "biomolekular"],
    ["penatu", "binatu"],
    ["bonafide", "bonafid"],
    ["bolpoin", "bolpen"],
    ["berengsek", "brengsek"],
    ["berewok", "brewok"],
    ["berangus", "brangus"],
    ["bungkuk", "bongkok"],
    ["berandal", "brandal"],
    ["bulu tangkis", "bulutangkis"],
    ["budi daya", "budidaya"],
    ["cakra buana", "cakrabuana"],
    ["capai", "capek"],
    ["capcai", "capcay"],
    ["cekik", "cekek"],
    ["cebur", "cebar-cebur"],
    ["sasis", "casis"],
    ["cecar", "cecer"],
    ["celsius", "celcius"],
    ["camilan", "cemilan"],
    ["cendera mata", "cenderamata"],
    ["cendekia", "cendikia"],
    ["cendekiawan", "cendikiawan"],
    ["cengkeram", "cengkram"],
    ["cengkerama", "cengkrama"],
    ["cerek", "ceret"],
    ["cerita", "ceritera"],
    ["cedera", "cidera"],
    ["cecak", "cicak"],
    ["cincau", "cingcau"],
    ["cokelat", "coklat"],
    ["sontek", "contek"],
    ["dai", "da'i"],
    ["dakwah", "da'wah"],
    ["dajal", "dajjal"],
    ["dongak", "dangak"],
    ["debit", "debet"],
    ["debitur", "debitor"],
    ["dedemit", "demit"],
    ["definisi", "defenisi"],
    ["disinfeksi", "desinfeksi"],
    ["disinfektan", "desinfektan"],
    ["disorientasi", "desorientasi"],
    ["distilasi", "destilasi"],
    ["detergen", "deterjen"],
    ["dividen", "deviden"],
    ["diagnosis", "diagnosa"],
    ["diode", "dioda"],
    ["desain", "disain"],
    ["diskotek", "diskotik"],
    ["diskret", "diskrit"],
    ["dus", "dos"],
    ["dramatisasi", "dramatisir"],
    ["dukacita", "duka cita"],
    ["efektivitas", "efektifitas"],
    ["ekshibisi", "eksibisi"],
    ["eksploitasi", "eksploitir"],
    ["ekstrem", "ekstrim"],
    ["elite", "elit"],
    ["ensiklopedia", "ensiklopedi"],
    ["anta", "ente"],
    ["erotis", "erotik"],
    ["paham", "faham"],
    ["faedah", "faidah"],
    ["familier", "familiar"],
    ["feminin", "feminim"],
    ["pikir", "fikir"],
    ["fon", "fonta"],
    ["fotosintesis", "fotosintesa"],
    ["frasa", "frase"],
    ["frekuensi", "frekwensi"],
    ["frustrasi", "frustasi"],
    ["polan", "fulan"],
    ["genting", "genteng"]
];

var words_count = words.length;
